server:
  port: 9002
spring:
  application:
    name: member-server
  # mysql
  datasource:
    url: jdbc:mysql://43.142.15.67:3306/wang?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Nacos
  cloud:
    nacos:
      discovery:
        server-addr: 43.142.15.67:8848
        username: nacos
        password: nacos
  # Redis
  redis:
    host: 43.142.15.67
    port: 6900
    password: 123456
    database: 0
    timeout: 1000

# mybatis
mybatis:
  mapper-locations: classpath:/com/wt/mapper/*Mapper.xml

# 打开mybatis的log日志
logging:
  level:
    com.wt.mapper: DEBUG