server:
  port: 9003

spring:
  application:
    name: gateway-server
  # Nacos
  cloud:
    nacos:
      discovery:
        server-addr: 43.142.15.67:8848
        username: nacos
        password: nacos

    # Gateway
    gateway:
      routes:
        - id: member-route
          uri: lb://member-server
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1
        - id: auth-route
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true  #使用小写服务名，默认是大写


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9001/rsa/publicKey' #配置RSA的公钥访问地址

  # Redis
  redis:
    host: 43.142.15.67
    port: 6900
    password: 123456
    database: 0
    timeout: 1000

#配置白名单路径
secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/auth/oauth/token"