server:
  port: 9001

spring:
  application:
    name: auth-server
  # Nacos
  cloud:
    nacos:
      discovery:
        server-addr: 43.142.15.67:8848
        username: nacos
        password: nacos
  # Redis
  redis:
    host: 43.142.15.67
    port: 6900
    password: 123456
    database: 0
    timeout: 1000


